name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Prettier
        run: npm run prettier:check
      - name: ESLint
        if: success() || failure()
        run: npm run eslint -- --max-warnings 0
