name: Node.js CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24.x
      - name: Build
        uses: ./.github/actions/build
      - name: Test
        run: npm test --ignore-scripts
